apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  containers:
  - name: webapp
    image: prongbang/skaffold-webapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
